// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAgencyAPI.Models;

#nullable disable

namespace TravelAgencyAPI.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    partial class TravelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelAgencyAPI.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Image");

                    b.Property<int?>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Images__3214EC07AD195F3E");

                    b.HasIndex("RatingId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly?>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<decimal?>("CoordinateX")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("CoordinateY")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<TimeOnly?>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Location__3214EC0701F88F5D");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.LocationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceAround")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Ticket")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Location__3214EC07D4417382");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationDetails");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.LocationTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "Language")
                        .IsUnique();

                    b.ToTable("LocationTranslations");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RatingValue")
                        .HasColumnType("decimal(2, 1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Ratings__3214EC070A4C58A9");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Tours__3214EC07D5AFDDFC");

                    b.HasIndex("UserId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.TourLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DayNumber")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OrderInDay")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TourLoca__3214EC07D1C11197");

                    b.HasIndex("LocationId");

                    b.HasIndex("TourId");

                    b.ToTable("TourLocations");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Interest")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC071A214DBB");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105340472FEA7")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.Image", b =>
                {
                    b.HasOne("TravelAgencyAPI.Models.Rating", "Rating")
                        .WithMany("Images")
                        .HasForeignKey("RatingId")
                        .HasConstraintName("FK__Images__RatingId__3D5E1FD2");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.LocationDetail", b =>
                {
                    b.HasOne("TravelAgencyAPI.Models.Location", "Location")
                        .WithMany("LocationDetails")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK__LocationD__Locat__2D27B809");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.LocationTranslation", b =>
                {
                    b.HasOne("TravelAgencyAPI.Models.Location", "Location")
                        .WithMany("Translations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.Rating", b =>
                {
                    b.HasOne("TravelAgencyAPI.Models.Location", "Location")
                        .WithMany("Ratings")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK__Ratings__Locatio__3A81B327");

                    b.HasOne("TravelAgencyAPI.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Ratings__UserId__398D8EEE");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.Tour", b =>
                {
                    b.HasOne("TravelAgencyAPI.Models.User", "User")
                        .WithMany("Tours")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Tours__UserId__31EC6D26");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.TourLocation", b =>
                {
                    b.HasOne("TravelAgencyAPI.Models.Location", "Location")
                        .WithMany("TourLocations")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK__TourLocat__Locat__35BCFE0A");

                    b.HasOne("TravelAgencyAPI.Models.Tour", "Tour")
                        .WithMany("TourLocations")
                        .HasForeignKey("TourId")
                        .IsRequired()
                        .HasConstraintName("FK__TourLocat__TourI__34C8D9D1");

                    b.Navigation("Location");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.Location", b =>
                {
                    b.Navigation("LocationDetails");

                    b.Navigation("Ratings");

                    b.Navigation("TourLocations");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.Rating", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.Tour", b =>
                {
                    b.Navigation("TourLocations");
                });

            modelBuilder.Entity("TravelAgencyAPI.Models.User", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
